export const videoData = [
  {
    id: "1",
    channelName: "Marques Brownlee",
    channelSubsCount: "20.9M subscribers",
    videoTitle: "Talking Tech and AI with Google CEO Sundar Pichai!",
    videoDuration: "14:20",
    videoViews: "4.3M views",
    videoUploadTime: "4 year ago",
    videoLink: "5puu3kN9l7c",
    channelLink: "@mkbhd",
  },
  {
    id: "2",
    channelName: "Markiplier",
    channelSubsCount: "38.6M subscribers",
    videoTitle: "Try Not To Laugh Challenge #9",
    videoDuration: "19:59",
    videoViews: "21M views",
    videoUploadTime: "8 year ago",
    videoLink: "mP0RAo9SKZk",
    channelLink: "@markiplier",
  },
  {
    id: "3",
    channelName: "SSSniperWolf",
    channelSubsCount: "35M subscribers",
    videoTitle: "Crazy Tik Toks Taken Moments Before DISASTER",
    videoDuration: "9:13",
    videoViews: "14M views",
    videoUploadTime: "5 year ago",
    videoLink: "FgjPQQeTh1w",
    channelLink: "@SSSniperWolf",
  },
  {
    id: "4",
    channelName: "Veritasium",
    channelSubsCount: "20.6M subscribers",
    videoTitle:
      " The Simplest Math Problem No One Can Solve - Collatz Conjecture",
    videoDuration: "22:09",
    videoViews: "45M views",
    videoUploadTime: "4 year ago",
    videoLink: "094y1Z2wpJg",
    channelLink: "@veritasium",
  },
  {
    id: "5",
    channelName: "CS Dojo",
    channelSubsCount: "1.95M subscribers",
    videoTitle: "Kadane's Algorithm to Maximum Sum Subarray Problem",
    videoDuration: "11:17",
    videoViews: "771k views",
    videoUploadTime: "10 year ago",
    videoLink: "86CQq3pKSUw",
    channelLink: "@CSDojo",
  },
  {
    id: "6",
    channelName: "MrBeast",
    channelSubsCount: "15M subscribers",
    videoTitle: "Anything You Can Fit In The Circle I’ll Pay For",
    videoDuration: "19:59",
    videoViews: "141M views",
    videoUploadTime: "6 year ago",
    videoLink: "yXWw0_UfSFg",
    channelLink: "@MrBeast",
  },
  {
    id: "7",
    channelName: "RealLifeLore",
    channelSubsCount: "7.92M subscribers",
    videoTitle: "Why Planes Don't Fly Over Tibet",
    videoDuration: "10.13",
    videoViews: "8.4M views",
    videoUploadTime: "5 year ago",
    videoLink: "fNVa1qMbF9Y",
    channelLink: "@RealLifeLore",
  },
  {
    id: "8",
    channelName: "VISION",
    channelSubsCount: "844k subscribers",
    videoTitle: "Inside The World's Biggest Passenger Plane",
    videoDuration: "7.12",
    videoViews: "9.9M views",
    videoUploadTime: "5 year ago",
    videoLink: "lFm4EM1juls",
    channelLink: "@adin",
  },
  {
    id: "9",
    channelName: "ThenX",
    channelSubsCount: "7.83M subscribers",
    videoTitle: "The SECRET to Super Human STRENGTH",
    videoDuration: "13.17",
    videoViews: "24M views",
    videoUploadTime: "8 year ago",
    videoLink: "ixmxOlcrlUc",
    channelLink: "@OFFICIALTHENXSTUDIOS",
  },
  {
    id: "10",
    channelName: "Business Insider",
    channelSubsCount: "10.5M subscribers",
    videoTitle:
      "How The World's Largest Cruise Ship Makes 30,000 Meals Every Day",
    videoDuration: "7.53",
    videoViews: "22M views",
    videoUploadTime: "6 year ago",
    videoLink: "R2vXbFp5C9o",
    channelLink: "@BusinessInsider",
  },
  {
    id: "11",
    channelName: "Destination Tips",
    channelSubsCount: "281k subscribers",
    videoTitle:
      "Dubai's Crazy Underwater Train and Other Things #Only in Dubai",
    videoDuration: "4.10",
    videoViews: "4.7M views",
    videoUploadTime: "5 year ago",
    videoLink: "0nZuYyXET3s",
    channelLink: "@Destinationtips",
  },
  {
    id: "12",
    channelName: "TED-Ed",
    channelSubsCount: "22.6M subscribers",
    videoTitle: "What would happen if you didn’t drink water? - Mia Nacamulli",
    videoDuration: "4.51",
    videoViews: "23M views",
    videoUploadTime: "10 year ago",
    videoLink: "9iMGFqMmUFs",
    channelLink: "@TEDEd",
  },
];
